### ISSUE TITLE
Parameter.load implicitly casts values with no user control

### ISSUE THREAD

**Issue by LeartS** [phcurado/parameter#66]
`Parameter.load` defaults to casting values and there doesn't seem to be a way to disable that behaviour.

Simple example to reproduce
```elixir
  defmodule UserPayload do
    use Parameter.Schema

    param do
      field :user_id, :string
    end
  end
```

```elixir
Parameter.load(UserPayload, %{"user_id" => false})
# {:ok, %{user_id: "false"}}
```

I would like to get an error when I get an invalid user payload, not an implicit cast. I'd argue that should be the default behaviour,
but I'd settle for an extra option in `Paramter.load/3` to explicitly disable it, e.g.

```elixir
Parameter.load(UserPayload, %{"user_id" => false}, implicit_casting: false)
# {:error, %{user_id: "invalid string type"}}
```

I know I could use `validate` first and then `load`, but that it's just ugly, redundant the goes against the functional [Parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) best practice.

**Comment by phcurado** [comment]
Hi @LeartS, the library does not perform strict parsing by design, as an example you can check the boolean parser where you will see that even strings or integers like "1" or 0 will be valid boolean values for casting. The reason for that is because this lib was designed for parsing values from external data, where this data may be unknown, returning unexpected values. Because of this, Parameter does it's best to parse the values by having this non strict behaviour.
For strict validation I created the `validate` function to fit this purpose.
